---
- hosts: vmlab
  user: student
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest

    - name: install EPEL repo
      yum:
        name: epel-release
        state: present

    - name: remove tree package
      yum:
        name: tree
        state: absent

    - name: set hostname
      hostname:
        name: kcpatel15

    - name: create user
      user:
        name: kcpatel15
        state: present
        groups: wheel
        append: yes

    - name: setup SSH directory
      file:
        path: /home/kcpatel15/.ssh
        state: directory
        mode: '0700'

    - name: copy authorized_keys
      copy:
        src: /home/student/.ssh/authorized_keys
        dest: /home/kcpatel15/.ssh/authorized_keys
        mode: '0600'

    - name: create directory structure
      file:
        path: /home/kcpatel15/ops445/lab{{ item }}
        state: directory
        mode: '0755'
      with_items:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
